#!/bin/bash
#
# Docker assumes an image named guvera/autopickle already exists. If it does not, run:
#
# docker build -t guvera/autopickle docker
#

REPO=${1:-/scratch/git/we7/radio-site}
PORT=${2:-4567}
CMD="ruby /autopickle/autopickle-gui.rb -f /repo"

IDS=$(docker ps --no-trunc | grep -v 'CONTAINER ID' | grep "0.0.0.0:$PORT->4567/tcp" | awk '{print $1}')

if [[ -n $IDS ]]; then
  echo "Removing previous AutoPickle container..."
  echo $IDS | xargs docker stop $ID 1>/dev/null
  echo $IDS | xargs docker rm $ID 1>/dev/null
  echo "Done :-)"
fi

docker run -d -p $PORT:4567 -w /autopickle -v $REPO:/repo -v `pwd`:/autopickle -t guvera/autopickle $CMD
